poll/urls.py
from django.urls import path

from . import views

app_name = 'poll'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:q_id>/vote/', views.vote, name='vote'),
    path('<int:q_id>/result/', views.result, name='result')
]

pollsapp/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import include, path

def hello(request):
    return HttpResponse('<h1>Hello Engineers 🤞</h1>')

def multiply(request, num):
    html = f'<h1>Table del {num}</h1>'
    for i in range(1, 11):
        html += f'<p>{ num } * { i } = { i * num }</p>'
    return HttpResponse(html)

def home(request):
    return render(request, 'home.html')

urlpatterns = [
    path('', home, name='home'),
    path('poll/', include('poll.urls')),
    path('admin/', admin.site.urls),
    path('hello/', hello, name='hello'),
    path('table/<int:num>/', multiply, name='multiply')
]

poll/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=150)
    pub_date = models.DateTimeField()
    
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    choice_text = models.CharField(max_length=100)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

poll/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Question, Choice
import json

# Create your views here.
def home(request):
    questions = Question.objects.all
    return render(
        request,
        'poll/home.html',
        {
            "questions": questions
        })

def vote(request, q_id):
    q = get_object_or_404(Question, pk=q_id)
    if request.method == "POST":
        try:
            choice_id = request.POST.get('choice')
            choice = q.choice_set.get(pk=choice_id)
            choice.votes += 1
            choice.save()
            return redirect('poll:result', q_id)
        except (KeyError, Choice.DoesNotExist):
            return render(request, 'poll/vote.html',{
                "question": q,
                "error_message": "Debes elegir algo :3"
                })
    return render(request, 'poll/vote.html',{
        "question": q,
        })

def result(request, q_id):
    # try:
    #     q = Question.objects.get(pk=q_id)
    # except Question.DoesNotExist:
    #     return redirect('poll:home')
    
    q = get_object_or_404(Question, pk=q_id)
    choices = q.choice_set.all()
    choice_text = json.dumps([choice.choice_text for choice in choices])
    votes = json.dumps([choice.votes for choice in choices])
    
    # data = {
    #     'question_text': question.question_text,
    #     'labels': labels,
    #     'votes': votes,
    # }
    return render (request, 'poll/result.html', {
        "question": q,
        "choice_text": choice_text,
        "votes": votes,
    })

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Encuestas | {% block title %}{% endblock %}</title>
</head>
<body>

    <div class="container">
        {% block content %}
          
        {% endblock %}
    </div>
    
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Welcome Home</h1>

    <a href="{% url 'poll:home' %}">Ir a Encuestas</a>
{% endblock %}

templates/poll/home.html
{% extends "base.html" %}

{% block title %}Encuestas{% endblock %}

{% block content %}
  
  <h1>Encuestas</h1>

  <ul>
      {% for q in  questions %}
        <li>
          <a href="{% url 'poll:vote' q.id %}">{{ q }}</a>
        </li>
        <li>
          <a href="{% url 'poll:result' q.id %}">Resultados</a>
        </li>
      {% endfor %}
  </ul>
{% endblock %}

templates/poll/result.html
{% extends "base.html" %}

{% block title %}
  Resultados
{% endblock %}

{% block content %}
  <h1>{{ question.question_text }}</h1>

  <ul>
    {% for c in question.choice_set.all %}
      <li>{{ c.choice_text }} - {{ c.votes }} voto{{ c.votes | pluralize }}</li>
    {% endfor %}
  </ul>

  <div class="canva" style="width: 500px; margin:0 auto;">
    <canvas id="myPieChart" width="400px" height="400px"></canvas>

  </div>
  <!-- Canvas para la gráfica de pastel -->
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script>
    const ctx = document.getElementById('myPieChart').getContext('2d');
    const choiceText = '{{ choice_text|escapejs }}';  // Convertir a JSON
    const votes = '{{ votes|escapejs }}';  // Convertir a JSON

    const chartData = {
        labels: JSON.parse(choiceText),
        datasets: [{
            label: 'Votos por Opción',
            data: JSON.parse(votes),
            backgroundColor: [
              'rgba(255, 99, 132, 0.2)',
              'rgba(54, 162, 235, 0.2)',
              'rgba(255, 206, 86, 0.2)',
              'rgba(75, 192, 192, 0.2)',
              'rgba(153, 102, 255, 0.2)',
              'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: 'rgba(75, 192, 192, 1)',
            borderWidth: 1
        }]
    };

    const myBarChart = new Chart(ctx, {
        type: 'bar',
        data: chartData,
        options: {
            responsive: true,
            plugins: {
                legend: {
                    position: 'top',
                },
                title: {
                    display: true,
                    text: 'Bar Chart of Votes'
                }
            }
        }
    });
</script>
  <hr>
  <a href="{% url 'poll:home' %}">Encuestas</a>
{% endblock %}

templates/poll/vote.html
{% extends "base.html" %}

{% block title %}Vota{% endblock %}

{% block content %}
  <h1>{{ question.question_text }}</h1>
  {% if error_message %}
    <div class="alert">
      <p>{{ error_message }}</p>
    </div>
  {% endif %}
  
  <form method="post">
    <!-- Para proteger los datos y además de que no servirá el formulario -->
    {% csrf_token %}
    {% for c in question.choice_set.all %}
    <input type="radio" name="choice" id="c_{{ c.id }}" value="{{ c.id }}">
    <label for="{{ c.id }}">{{ c.choice_text }}</label>
    {% endfor %}
    <input type="submit" value="Votar">
  </form>

{% endblock %}